### PR TITLE
Documentation for the whole project

### PR DESCRIPTION
**Pull request by CrocAx**
# PR summary

## This PR is created for everyone to combine the documentation about the all parts of our project.

I have started by adding `frontend` docs and maybe you guys have better suggestions what we can add to this.

Would be nice to finish this ASAP! @martimolanes @Andebugulin

### CODE REVIEW

**Comment by CrocAx** [comment]
I don't think that we need to make a bulky documentation. Since we have the database docs already, we need to add the `backend` docs and maybe improve the `frontend` if needed. Then when we can just make frontend and backend into one file and then merge it.

**Comment by Andebugulin** [comment]
## `docs` changes that I made:

#### addition
- context management
- our routing pages
- reusable components

---

#### deletion
- database schema useless comments

---

#### change 
- application usage doc, correction about our routings.

**Comment by Andebugulin** [comment]
I propose to devide our docs:
---
imagine structure like this, feels good:

```lua
docs/
├── <some README navigation or usage or both>
├── client/
│   └── <frontend related docs>
├── server/
│   └── <backend related docs>
├── database/
│   └── <database related docs>
```

**Comment by Andebugulin** [comment]
Hello, I will try to implement some server docs as well, in order to have a base to work with, of course, you can change whatever you want to.

**Comment by Andebugulin** [comment]
**Documentation Updates:**

---
- Enhanced root README links.
- Added database setup README.
- Updated client and server READMEs.

---

Feel free to provide any suggestions on how to improve it.

**Review by CrocAx — COMMENTED** [review]
LGTM! The new structure is beautiful! I don't think there is a need for anymore changes

**Comment by CrocAx** [comment]
I think this can be merged

**Review by martimolanes — APPROVED** [review]
LGTM this is ready

**Pull request merged**
