### PR TITLE
Backend frontend communication

### PR DESCRIPTION
**Pull request by Andebugulin**
## This PR links the `Tasks` and `Activities` components to our  backend, tag functionality is introduced

---

### Key updates include:

1. Implementing  communication with api routes for data handling in Tasks and Activities hooks
    - `/activities`
    - `/tasks`
    - `/tags`
    - `and nested routes`

2. Integrating tag support to categorize tasks and activities.

3.  Enhancing front-end responsiveness to backend changes.

### CODE REVIEW

**Review by CrocAx — COMMENTED** [review]
Very good start! I have checked the functionality of the API through `/dashboard/activities` route in frontend and the communication by using hooks to the backend works very well. Keep up the great work!

**Comment by Andebugulin** [comment]
### Currently, activities and tasks are not fully implemented, but I want you to check whether you are satisfied with how they work right now or not.

@CrocAx @martimolanes 

### Thank you for your feedback!

**Comment by Andebugulin** [comment]
**Main functionality of the PR has been implemented**
  - tags
  - activities
  - tasks
  
 additionally `charts` were made for the `statistics`

---
Feel free to suggest your ideas, or recomendations

**Review by CrocAx — COMMENTED** [review]
Looks great! The visuals on the application look fantastic! The tags look very great. There are still some flaws with the `activityid` when creating new task.

image
  
Maybe those things are yet to be done, but things I found missing:  

 - There is no way to assign the activity to the task as vice versa.
 - When creating activity there is no way to set task status to `planning`, so `planning` tab is kinda useless in a way.
 - When creating activity, there static 3 types of activities that do not correlate to the database activity types.
 
image

These things I saw that still need some fixing. Everything else looks super clean. Keep up the great work!

**Comment by Andebugulin** [comment]
Hello, I fixed issues you specified.

I should fix more *typescript errors* , but generally I belive that the part is almost ready to be merged.

---
### Please, put your own thoughts on what should i change or what else we shold implement

> in my opinion, everything is almsot done!

**Comment by Andebugulin** [comment]
### Hello, The issue with linking activities was discovered and fixed, now filtering and activity linking are two separate things!

---
Please, feel free to suggest new ideas or implementations.
Your feedback is highly appreciated. 

---

As well, please, I would appreciate little bit of help with styling and that sortof things, I will try to do something great soon. But I am running out of time. So, if you just could contribute little bit with styling :) @CrocAx  @martimolanes 
:+1:  Have a good day.

**Comment by CrocAx** [comment]
> ### Hello, The issue with linking activities was discovered and fixed, now filtering and activity linking are two separate things!
> Please, feel free to suggest new ideas or implementations. Your feedback is highly appreciated.
> 
> As well, please, I would appreciate little bit of help with styling and that sortof things, I will try to do something great soon. But I am running out of time. So, if you just could contribute little bit with styling :) @CrocAx @martimolanes 👍 Have a good day.

Great job! Everything now works very well! I think styling should be made in other PR, but since we don't have a lot of time, I can help you with that.

**Comment by CrocAx** [comment]
## Added new styling for `Tasks`, `Activities`, `Statistics`.

Change log:
 - Changed **Tasks** default tab on open to `All Tasks`
 - Added `Add` buttons in **Tasks** and **Activities**
 - Added margins to pages for better looks
 - Added search bar in **Activities**

**Review by CrocAx — APPROVED** [review]
@Andebugulin Code looks great! If there is no more changes needed, we can merge this!

**Comment by Andebugulin** [comment]
@CrocAx Thaks for your approval, then, I will fix `typescript type errors` and we merge it.

**Comment by Andebugulin** [comment]
@CrocAx  Thank you a lot, for this work of art job. 

I really like the styling and your improvements. Amazing. 

---
### Changes from previos comment:

- type errors are gone
- changed dates on activity page to be more user friendly
- minor styling fixes

---
I think we are ready to ```merge``` 
:+1:

**Review by CrocAx — APPROVED** [review]
LGTM! Super great work! Lets merge this!

**Pull request merged**
