### PR TITLE
Add express API backend with Sequelize Integration

### PR DESCRIPTION
**Pull request by martimolanes**
This PR introduces an Express API backend with Sequelize ORM support, enhancing our application's ability to interact with the PostgreSQL database. The key changes include:

1. **Express Setup:** Configured Express to serve as our application's API server.
2. **Sequelize Integration:** Set up Sequelize to manage our PostgreSQL database operations. Defined models and associations to map our application's business logic to the database schema.
3. **API Routes:** Added Express routes to handle API requests, leveraging Sequelize for data retrieval and manipulation.

By integrating Express and Sequelize, we've established a robust backend that can efficiently handle client requests and interact with our database.

### Target
- Implement two accesible api routes `/tasks` and `/activities` that retrieve all the tasks or activities in json format.

Please review the changes and let me know if any adjustments are required.

### CODE REVIEW

**Comment by martimolanes** [comment]
I need some check about the progress and the direction of this PR, @Andebugulin, @CrocAx, take your time to review the general direction of it.

**Comment by martimolanes** [comment]
I have some Work In Progress in the implementation of `/tasks` and `/activities`, now i want to improve and establish the final format of the JSON response.

**Comment by martimolanes** [comment]
`/activities`
```json
[
  {
    "id": 3,
    "title": "Chess Tournament Preparation",
    "description": "Preparation plan for national chess tournament",
    "url": null,
    "startDate": "2024-04-12T07:28:35.914Z",
    "endDate": "2024-06-12T07:28:35.914Z",
    "ActivityType": {
      "id": 2,
      "name": "Entertainment"
    },
    "Status": {
      "id": 1,
      "title": "Planning",
      "style": "#FFA07A"
    }
  },
  {
    "id": 2,
    "title": "Marathon Training",
    "description": "Training schedule for upcoming marathon",
    "url": null,
    "startDate": "2024-04-12T07:28:35.914Z",
    "endDate": "2024-10-12T07:28:35.914Z",
    "ActivityType": {
      "id": 3,
      "name": "Exercise"
    },
    "Status": {
      "id": 2,
      "title": "Ongoing",
      "style": "#20B2AA"
    }
  },
  {
    "id": 1,
    "title": "Python Programming Course",
    "description": "An intensive course to master Python programming",
    "url": "http://pythoncourse.com",
    "startDate": "2024-04-12T07:28:35.914Z",
    "endDate": "2024-07-12T07:28:35.914Z",
    "ActivityType": {
      "id": 4,
      "name": "Educational"
    },
    "Status": {
      "id": 1,
      "title": "Planning",
      "style": "#FFA07A"
    }
  }
]
```
not yet implemented:
- Tags.
What do you think about the format for importing from frontend @Andebugulin @CrocAx

**Comment by martimolanes** [comment]
`/tasks`
```json
[
  {
    "id": 1,
    "name": "Install Python",
    "content": "Download and install the latest version of Python",
    "startDate": "2024-04-12T07:28:35.915Z",
    "endDate": "2024-04-13T07:28:35.915Z",
    "Tags": [
      {
        "id": 4,
        "name": "Technology",
        "color": "#DAA520",
        "TaskTag": {
          "taskid": 1,
          "tagid": 4
        }
      }
    ],
    "Activity": {
      "id": 1,
      "title": "Python Programming Course",
      "description": "An intensive course to master Python programming",
      "url": "http://pythoncourse.com",
      "startDate": "2024-04-12T07:28:35.914Z",
      "endDate": "2024-07-12T07:28:35.914Z",
      "activitytype": 4,
      "status": 1
    }
  },
  {
    "id": 2,
    "name": "Daily 5K Run",
    "content": "Run 5 kilometers every day to build stamina",
    "startDate": "2024-04-12T07:28:35.915Z",
    "endDate": "2024-05-12T07:28:35.915Z",
    "Tags": [
      {
        "id": 3,
        "name": "Fitness",
        "color": "#2E8B57",
        "TaskTag": {
          "taskid": 2,
          "tagid": 3
        }
      }
    ],
    "Activity": {
      "id": 2,
      "title": "Marathon Training",
      "description": "Training schedule for upcoming marathon",
      "url": null,
      "startDate": "2024-04-12T07:28:35.914Z",
      "endDate": "2024-10-12T07:28:35.914Z",
      "activitytype": 3,
      "status": 2
    }
  },
  {
    "id": 3,
    "name": "Study Chess Openings",
    "content": "Study and memorize key chess openings",
    "startDate": "2024-04-12T07:28:35.915Z",
    "endDate": "2024-04-26T07:28:35.915Z",
    "Tags": [
      {
        "id": 2,
        "name": "Entertainment",
        "color": "#DC143C",
        "TaskTag": {
          "taskid": 3,
          "tagid": 2
        }
      }
    ],
    "Activity": {
      "id": 3,
      "title": "Chess Tournament Preparation",
      "description": "Preparation plan for national chess tournament",
      "url": null,
      "startDate": "2024-04-12T07:28:35.914Z",
      "endDate": "2024-06-12T07:28:35.914Z",
      "activitytype": 2,
      "status": 1
    }
  }
]
```
not implemented:
- We need an example of a task with multiple tags

Doubts:
- I dunno if adding the associated `Activity` of the `Task` is a good idea, or would be better to have only the id, and access to a future `/activities/:id` route to get the information of this activity. For the moment, adding `Activity` breaks the injection of other object inside it (_e. g. status and activitytype_).

**Comment by martimolanes** [comment]
I implemented the lasts parts, now we need to discuss about showing the `Activity` in the `Task` or only the `activityid`

**Review by CrocAx — COMMENTED** [review]
LGTM! I think that adding activity to the task itself feels too overcrowded. The 2nd idea is better, because I think we can link the tasks to the activities and calling activity with `id` will make it more flexible. So far the structure looks great. The task tag example will be possible when we have the start of frontend to backend connection. Keep it up! 👌

**Comment by martimolanes** [comment]
> LGTM! I think that adding activity to the task itself feels too overcrowded. The 2nd idea is better, because I think we can link the tasks to the activities and calling activity with `id` will make it more flexible. So far the structure looks great. The task tag example will be possible when we have the start of frontend to backend connection. Keep it up! 👌

Thanks for your opinion, I think as well is the best approach. I think is ready for merging!

**Comment by martimolanes** [comment]
This is the final JSON responses to the examples in the db

`/tasks`
```json
[
  {
    "id": 1,
    "name": "Install Python",
    "content": "Download and install the latest version of Python",
    "startDate": "2024-04-12T09:37:24.655Z",
    "endDate": "2024-04-13T09:37:24.655Z",
    "activityid": 1,
    "Tags": [
      {
        "id": 4,
        "name": "Technology",
        "color": "#DAA520"
      },
      {
        "id": 3,
        "name": "Fitness",
        "color": "#2E8B57"
      }
    ]
  },
  {
    "id": 2,
    "name": "Daily 5K Run",
    "content": "Run 5 kilometers every day to build stamina",
    "startDate": "2024-04-12T09:37:24.655Z",
    "endDate": "2024-05-12T09:37:24.655Z",
    "activityid": 2,
    "Tags": [
      {
        "id": 3,
        "name": "Fitness",
        "color": "#2E8B57"
      }
    ]
  },
  {
    "id": 3,
    "name": "Study Chess Openings",
    "content": "Study and memorize key chess openings",
    "startDate": "2024-04-12T09:37:24.655Z",
    "endDate": "2024-04-26T09:37:24.655Z",
    "activityid": 3,
    "Tags": [
      {
        "id": 2,
        "name": "Entertainment",
        "color": "#DC143C"
      }
    ]
  }
]
```
`/activities`
```json
[
  {
    "id": 1,
    "title": "Python Programming Course",
    "description": "An intensive course to master Python programming",
    "url": "http://pythoncourse.com",
    "startDate": "2024-04-12T09:37:24.654Z",
    "endDate": "2024-07-12T09:37:24.654Z",
    "ActivityType": {
      "id": 4,
      "name": "Educational"
    },
    "Status": {
      "id": 1,
      "title": "Planning",
      "style": "#FFA07A"
    },
    "Tags": [
      {
        "id": 4,
        "name": "Technology",
        "color": "#DAA520"
      }
    ]
  },
  {
    "id": 2,
    "title": "Marathon Training",
    "description": "Training schedule for upcoming marathon",
    "url": null,
    "startDate": "2024-04-12T09:37:24.654Z",
    "endDate": "2024-10-12T09:37:24.654Z",
    "ActivityType": {
      "id": 3,
      "name": "Exercise"
    },
    "Status": {
      "id": 2,
      "title": "Ongoing",
      "style": "#20B2AA"
    },
    "Tags": [
      {
        "id": 3,
        "name": "Fitness",
        "color": "#2E8B57"
      }
    ]
  },
  {
    "id": 3,
    "title": "Chess Tournament Preparation",
    "description": "Preparation plan for national chess tournament",
    "url": null,
    "startDate": "2024-04-12T09:37:24.654Z",
    "endDate": "2024-06-12T09:37:24.654Z",
    "ActivityType": {
      "id": 2,
      "name": "Entertainment"
    },
    "Status": {
      "id": 1,
      "title": "Planning",
      "style": "#FFA07A"
    },
    "Tags": [
      {
        "id": 2,
        "name": "Entertainment",
        "color": "#DC143C"
      }
    ]
  }
]
```

**Review by CrocAx — APPROVED** [review]
Looks very good! Great work!

**Review by Andebugulin — COMMENTED** [review]
**Great Job,** @martimolanes 
---
You’ve done a thorough job on the implementation in `/routes/task.ts`. The approach you've taken for handling `/:id` is clean and straightforward.

I have a question regarding the absence of `/:id` in `/routes/activity.ts`. Was this decision based on specific requirements, or is it something we might want to add for consistency? If it was omitted by design, could you elaborate on the reasoning? Apart from that, code looks clean and I like your approach, keep it up.

Looking forward to your thoughts!

**Comment by martimolanes** [comment]
yes, this is going to be in the next PR

**Pull request merged**
