### PR TITLE
Frontend styling

### PR DESCRIPTION
**Pull request by CrocAx**
# PR summary

## Main fixes:

 - Implemented new tabs system for `tasks`. Now tasks are being filtered by two different statuses: `In Progress` and `Completed`.
 - Changed visual style for `tasks` and `activities`. Tasks now has a board style and the activities are in the table format.
 - Implemented `framer-motion` dependency for the route transitions. Now the animations look more smooth and doesn't break.

## Small changes: 

- Fixed logo rendering on routes.

### CODE REVIEW

**Comment by CrocAx** [comment]
By checking the database structure, I suppose there will be a need to update task statuses, because so far in this PR, there is only `In Progress` and `Completed` which do no really go in the correct way of our data structure.

**Don't merge this change**, I will work on this thing.

**Comment by martimolanes** [comment]
Okey, for the moment this looks supergood, but dont make the PR to big :)
Insane work :+1:

**Comment by CrocAx** [comment]
> Okey, for the moment this looks supergood, but dont make the PR to big :) Insane work 👍

Thanks for your comment! This should be a small change :)

**Comment by Andebugulin** [comment]
Great job, @CrocAx 
---
Your styling is neat and the code is clean. Regarding the user experience on the activities, tasks, and dashboard pages, the content seems a bit left-sided. I suggest centering it to enhance visual balance. What are your thoughts on making this adjustment?

Looking forward to your thoughts!

**Comment by CrocAx** [comment]
> ## Great job, @CrocAx
> Your styling is neat and the code is clean. Regarding the user experience on the activities, tasks, and dashboard pages, the content seems a bit left-sided. I suggest centering it to enhance visual balance. What are your thoughts on making this adjustment?
> 
> Looking forward to your thoughts!

Thanks for the idea! I have looked into this and this is what I made.

image

Tasks page will stack with tasks, now it looks left-sided, but when it fills up with tasks, it will look great.

As example:

image


I was not sure what you mean about the activities page, it is a table and it is in the centre.

I am going to finish this PR and then we can open another for some more visual changes if needed

**Comment by CrocAx** [comment]
# New features:

I have done some changes to the frontend. It is not much, but the functionality is way better.

- Task tabs are now matching the status of our database task structure 
- Updated mock API to visualise the tasks on the new tabs
- Dashboard is now centered

## Additional small change:
Changed so in the landing page the `Get Started` button now changes from mouse to pointer

**Review by martimolanes — APPROVED** [review]
Lgtm! merge merge merge

**Comment by Andebugulin** [comment]
**Good job, @CrocAx !**

LGTM! We can merge it!

**Pull request merged**
