### PR TITLE
Frontend

### PR DESCRIPTION
**Pull request by Andebugulin**
**PR Summary**

- Implemented Context API for dynamic data handling in Dashboard, Tasks, and Activities components.
- Enabled CRUD functionalities for Tasks and Activities, allowing add, edit, and delete operations.
- Updated Dashboard to dynamically display data summaries.
- Improved UI styling for clarity and better user experience.

# Don't merge this PR
   - this PR was made for further development and conversations

### CODE REVIEW

**Comment by Andebugulin** [comment]
## forgot to mention, if you want to test it, i used routing, so install it via bun. 
---
#### (I am not sure whether bun packages were updated or not in my commits)
--- 

- docs should be provided
- packages should be automated

```
bun add react-router-dom
```

**Comment by martimolanes** [comment]
hello andebugulin! thank you for start this PR!
First, small tip, if you dont this PR to get merged, you can convert it to a draft PR in the right part of the screen with the reviews.
> (I am not sure whether bun packages were updated or not in my commits)

The packages that you add as dependencies to the project running `bun add ...` are included to the package.json. So, each person can install it with `bun install` when they clone the repo.

**Review by martimolanes — COMMENTED** [review]
LGTM! keep on working
I will test it once the PR is more advanced

**Comment by martimolanes** [comment]
pull the changes, i solved the conflicts with the main branch

**Review by CrocAx — COMMENTED** [review]
Looks good!

**Comment by martimolanes** [comment]
how is evolving this PR? Any progress or something blocking it?

**Pull request closed without merging**
